### ISSUE TITLE
Bisq at Feb 6th 2018 Malmö Bitcoin Users meetup

### ISSUE THREAD

**Issue by cbeams** [bisq-network/events#12]
Per https://twitter.com/remyers_/status/959341418635505665:

![image](https://user-images.githubusercontent.com/301810/35733485-e0912f86-081d-11e8-9e17-1fcd28739a41.png)

**Comment by cbeams** [comment]
Closing as complete. Any update / debrief on how this went, @remyers or @meapistol?

From https://www.meetup.com/Malmo-Bitcoin-Users/events/cdlbcpyxdbkb/:

![image](https://user-images.githubusercontent.com/301810/36814680-988f290c-1cd8-11e8-8604-9a5bd6e7b064.png)

**Comment by meapistol** [comment]
The meetup started by Richard Myers giving a brief introduction to the need for decentralised exchanges. Then I (mep) presented Bisq at a fairly high technical level, since it turned out that the audience was sophisticated. This presentation included the DAO and how it will work. Following the presentation a complete trade, including placing an offer, was executed using a projector. A member of the public took the offer and paid using Swish. At the end Richard concluded the meeting. The audience was small, about 15 people, but they had very initiated questions including comments about MimbleWimble. This was the first in a series of meetings where the next one will concern remittances using Bitcoin by a Swedish startup - PlingPay.

**Comment by cbeams** [comment]
Nice! Thanks for the write-up.
